[storage]
working_dir = "/workspace/data"

[metrics]
enabled = true
prometheus_port = 9153

[ordinals.db]
database = "ordinals"
host = "postgres"  # Changed from localhost to postgres for Docker networking
port = 5432
username = "postgres"
password = "postgres"

[ordinals.meta_protocols.brc20]
enabled = true
lru_cache_size = 10000

[ordinals.meta_protocols.brc20.db]
database = "brc20"
host = "postgres"  # Changed from localhost to postgres for Docker networking
port = 5432
username = "postgres"
password = "postgres"

[runes]
lru_cache_size = 10000

[runes.db]
database = "runes"
host = "postgres"  # Changed from localhost to postgres for Docker networking
port = 5432
username = "postgres"
password = "postgres"

[bitcoind]
network = "mainnet"
rpc_url = "http://bitcoind:8332"  # Changed from localhost to bitcoind for Docker networking
rpc_username = "devnet"
rpc_password = "devnet"
zmq_url = "tcp://bitcoind:18543"  # Changed from 0.0.0.0 to bitcoind for Docker networking

[resources]
ulimit = 2048
cpu_core_available = 6
memory_available = 16
bitcoind_rpc_threads = 2
bitcoind_rpc_timeout = 15 