# start docker image
# run postgres
# run cargo test --workspace
# run cargo bitcoin-indexer-clippy
# display the output of both

version: '3.7'
services:
  postgres:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-environment:
    build:
      context: .
      dockerfile: components/test-environment.dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      RUST_BACKTRACE: full
      LIBCLANG_PATH: /usr/lib/llvm-11/lib:/usr/lib:/usr/lib/x86_64-linux-gnu
      LD_LIBRARY_PATH: /usr/lib/llvm-11/lib:/usr/lib:/usr/lib/x86_64-linux-gnu
      BINDGEN_EXTRA_CLANG_ARGS: "-I/usr/lib/llvm-11/include"
      ROCKSDB_LIB_DIR: /usr/lib/x86_64-linux-gnu
      ROCKSDB_STATIC: 1
      ORDINALS_PGHOST: postgres
      ORDINALS_PGPORT: 5432
      ORDINALS_PGUSER: postgres
      ORDINALS_PGPASSWORD: postgres
      ORDINALS_PGDATABASE: postgres
      ORDINALS_SCHEMA: public
      BRC20_PGHOST: postgres
      BRC20_PGPORT: 5432
      BRC20_PGUSER: postgres
      BRC20_PGPASSWORD: postgres
      BRC20_PGDATABASE: postgres
      BRC20_SCHEMA: public
    working_dir: /app
    command: cargo test --workspace
    tty: true