[package]
name = "ordhook-sdk-js"
version = "0.5.0"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
ordhook = { path = "../ordhook-core" }
hiro-system-kit = "0.3.1"
crossbeam-channel = "0.5.6"

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-6", "channel-api", "event-queue-api", "try-catch-api", "promise-api", "task-api"]

[dependencies.num]
version = "0.2"
default-features = false
